media_build: add new backport patch v2.6.35_kfifo.patch
The media_build tree fails to build with kernels 2.6.33, .34 and .35:

In file included from /home/hans/work/build/media_build/v4l/rc-main.c:22:0:
/home/hans/work/build/media_build/v4l/rc-core-priv.h:38:26: error: field 'kfifo' has incomplete type
make[3]: *** [/home/hans/work/build/media_build/v4l/rc-main.o] Error 1
make[3]: *** Waiting for unfinished jobs....

This is due to patch http://patchwork.linuxtv.org/patch/9914/ .
Patch http://patchwork.linuxtv.org/patch/10274/ fixed the issue with 2.6.32,
but the proper fix is to revert patch 9914 for kernel 2.6.35,
adding a new backport patch.

Tested with kernels 2.6.32 and 2.6.33.

Signed-off-by: Gianluca Gennari <gennarone@gmail.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>