media_build: disable VIDEO_SMIAPP driver on kernels older than 2.6.34
The new 'smiapp' driver requires 'gpio_request_one':

media_build/v4l/smiapp-core.c:2333: error: implicit declaration of function 'gpio_request_one'

that was first introduced in kernel 2.6.34, so let's disable it on older kernels.

Signed-off-by: Gianluca Gennari <gennarone@gmail.com
Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>